### ISSUE TITLE
Initialization of the unit label for a PSD obj is not working properly 

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#112]
When the unit is None, it still presents in the label.

**Comment by fzhu2e** [comment]
Fixed in commit a4ac560f702e64255f60fadb1dd90242109a8059.

**Comment by CommonClimate** [comment]
I want to flag here that the concept of "unit" (singular) is not very common in English. Most people will implicitly  interpret this as plural and use "years" instead of "year", for instance, which means that adding the extra s on some plots will result is "yearss". Pretty silly. Given that other common units will be appreviation (e.g. ka, kyr, Ma, etc), I think we should consider unitS (plural) and dispense with adding an extra "s"

**Comment by fzhu2e** [comment]
Modified in commit 27a82ea. Now the behavior is as below:

If the users specified `time_unit` belongs to one of below categories excluding `kage_units`, the `period_unit` will be set to `yrs`; if belongs to `kage_units`, the `period_unit` will be set to `kyrs`. Otherwise, if `time_unit` ends with "s", then the `period_unit` will be the same as the `time_unit`; otherwise, an "s" will be appended to `time_unit` to get the `period_unit`.
```
    age_units = ['year B.P.','yr B.P.','yr BP','BP','yrs BP','years B.P.',\
                 'yr. BP','yr. B.P.', 'cal. BP', 'cal B.P.', \
                 'year BP','years BP']
    kage_units = ['kyr BP','kaBP','ka BP','ky','kyr','kyr B.P.', 'ka B.P.']
    year_units = ['AD','CE','year C.E.','year A.D.', 'year CE','year AD',\
                  'years C.E.','years A.D.','yr CE','yr AD','yr C.E.'\
                  'yr A.D.', 'yrs C.E.', 'yrs A.D.', 'yrs CE', 'yrs AD']
    undefined = ['years', 'yr','year','yrs']
```
