### ISSUE TITLE
Frequency axis for the Lomb-Scargle method

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#114]
**Describe the bug**
L-S method shows a singularity at the Nyquist frequency. 

**To Reproduce**
generate a harmonic, evenly spaced series ts and apply `ts.spectral(method = 'lomb_scargle)`. 
**Expected behavior**
There should be no singularity at the Nyquist frequency
**Screenshots**

![image](https://user-images.githubusercontent.com/13760223/99010030-02ab3580-24fe-11eb-8192-5b7ec51b1a3d.png)

**Additional context**
Requires updating the method generating the frequency vector for the L-S method.

**Comment by khider** [comment]
Issue is due to unevenly vs evenly spaced signal for the last frequency point (regardless whether it's the Nyquist frequency). 

See here: https://github.com/KnowledgeCaptureAndDiscovery/autoTS/blob/master/notebooks/Methods/Lomb%20Scargle%20Performance%20on%20Evenly%20Spaced%20Signal.ipynb 

This is a problem with the original implementation rather than the Pyleoclim wrapper. Suggest putting a warning if the series is evenly-spaced that there might be a spurious value at high frequency end.

**Comment by khider** [comment]
Fixed in commit [715ac75](https://github.com/LinkedEarth/Pyleoclim_util/commit/715ac751a5902f3f5ffc3c2ad5a87ec5311d951c)
