### ISSUE TITLE
Binning returns discontinuous timeseries

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#139]
**Describe the bug**
On many unevenly spaced timeseries, `bin()` (whether called via the UI as in `ts.bin()`, or directly via tsutils) produces a discontinuous output full of NaNs, as in this case:

![image](https://user-images.githubusercontent.com/13760223/107273198-94deaf00-6a03-11eb-9458-aa7606fd30c5.png)

**To Reproduce**
Steps to reproduce the behavior: see paleohackathon notebook 3, d18Osw example. 

**Expected behavior**
No NaNs

**Comment by CommonClimate** [comment]
Suggest harmonizing `bin()` to behave more like `interp()`, which works well. Note that `grid_properties` can be re-used by both.

**Comment by khider** [comment]
Bin was changed to take on an additional arguments that uses the maximum dt in the time series instead of the median, resulting in an evenly-spaced series. The new argument is a bool. If evenly_spaced is set to False, then uses the median. If bin_size is set, evenly_spaced is ignored.

See commit [931e7956](https://github.com/LinkedEarth/Pyleoclim_util/commit/931e79564e505cdacbb8236242fbd032006843fc)
