### ISSUE TITLE
p-value formatting

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#147]
**Is your feature request related to a problem? Please describe.**

When representing p-values with a fixed number of decimal places (say 2), very small values end up looking like "0.00", which is not meaningful. One could of course show the full value, but in many cases this is impractical. 

**Describe the solution you'd like**
Methods that return a diagnostic output involving p-values, whether text or visual (e.g.` correlation()`), should implement a scheme such as: 
- p > 0.01, show with 2 decimals.
- p < 0.01, show "p < 10^{-n}" where n is the closest order of magnitude  

A dedicated function (e.g. `prob_format`) could be used for that purpose.

**Comment by fzhu2e** [comment]
Fixed in commit 19202ccf

**Comment by khider** [comment]
Please link figures/tables

**Comment by fzhu2e** [comment]
There are two possible styles for print in the implemented function `pval_format`:
1. `style='float'` e.g. p < 0.01
<img width="708" alt="Screen Shot 2021-04-06 at 1 36 13 PM" src="https://user-images.githubusercontent.com/1380844/113775414-84824200-96dd-11eb-9f44-164adf6526c5.png">

2. otherwise, e.g. p < 10^{-2}
<img width="695" alt="Screen Shot 2021-04-06 at 1 37 21 PM" src="https://user-images.githubusercontent.com/1380844/113775424-86e49c00-96dd-11eb-814f-362e3a4642d6.png">

The 2nd style would be good if it could be compiled as a LaTeX equation, but for print, we can only print normal text and that looks too cumbersome in a table and inconsistent with other normal float p-values.

**Comment by fzhu2e** [comment]
Using exponential notation by default in commit 56d40981e95eca3f3086edac48522d25d42eccc9
