### ISSUE TITLE
Problem in running the Summary plot code

### ISSUE THREAD

**Issue by PriyantanG** [LinkedEarth/Pyleoclim_util#233]
*When I have run the code given in your repository all the parts ran well but when it came to the summary plot part it's showing an error of unexpected statement- "summary_plot() got an unexpected keyword argument 'n_signif_test'. I am hereby attaching the screen shot of the problem with this issue. 
![Problem_Pyleoclim](https://user-images.githubusercontent.com/109213803/178708033-9778504c-00e0-46e2-b824-e99edca360f3.png)
"**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PriyantanG** [comment]
Hello! While checking the version of pyleoclim it's showing "module
pyleoclim has no attribute _version_". I am using Jupyter note book on
python 3.10.
Thank you

Sincerely,

Priyantan Gupta

Department Of Geology & Geophysics

Indian Institute Of Technology, Kharagpur

**Comment by PriyantanG** [comment]
I am using the version 0.8.1 of pyleoclim package.
Thank you.

Sincerely,

Priyantan Gupta

Department Of Geology & Geophysics

Indian Institute Of Technology, Kharagpur

**Comment by CommonClimate** [comment]
Hello @PriyantanG , a couple of things:

- there was indeed a bug in the notebook, in the sense that it was out of sync with the latest Pyleoclim version. To add insult to injury, the documentation also still was referring to the deprecated argument `n_signif_test'. The former issue was resolved in 75a862c9288164a8b60bcd1016b08183911f7d68; the latter was resolved in the Development branch (cc25b34ced05000ea41d7273dfb653835ca015c2), and will be incorporated into the next release (0.8.2). 
- For all programming matters, I highly suggest cut&paste instead of typing:  Python told you `module
pyleoclim has no attribute _version_` because the command you typed was `pyleo._version_`, instead of the `pyleo.__version__` that @khider recommended (two underscores instead of one). If you don't follow instructions correctly, you can't expect correct results!
- not also for future bug reports that the bottom of the form was asking you for the OS and software versions, and in the future it will speed up our response process if you fill that out right away. 

Hope this helps, and wishing you a happy Pyleocliming!

**Comment by PriyantanG** [comment]
Thank you very much.

Sincerely,

Priyantan Gupta

Department Of Geology & Geophysics

Indian Institute Of Technology, Kharagpur
