### ISSUE TITLE
Removing seaborn's distplot dependency

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#257]
**Describe the bug**
Several of our functions, namely `Series.distplot()` and `LipdSeries.dashboard()`, use [distplot](https://seaborn.pydata.org/generated/seaborn.distplot.html), which is about to be deprecated.  This is not a bug yet, but it will be very soon if we don't change things.

**Suggestions**
Replace `distplot` by `histplot` or `displot`, whichever is more appropriate. 

Tagging @alexkjames because I seem to recall he did some work on this already.

**Comment by CommonClimate** [comment]
As Deborah reminds us on Slack: 

> "dashboard re-uses the Series.distplot()  function as is. So unless there is a change to the parameters, no need to fix the dashboard once distplot is fixed".

 I would support renaming  `Series.distplot()` to  `Series.histplot()` to align to seaborn's terminology, and re-using that within `dashboard()`.

**Comment by khider** [comment]
I would suggest making sure that none of our materials: tutorials and the likes uses distplot(). Otherwise, I'm in favor or not renaming right away but have a depreciation warning first so we can take care of it when we redo hackathon and tutorial materials. And give other people some time to adjust to yet another API change.

**Comment by alexkjames** [comment]
series addressed by 58510097c82be8187249d17e940e30042515c062

**Comment by alexkjames** [comment]
ensembleseries addressed by 4563676f5f47630f031f2da6cce7474758a005ba
