### ISSUE TITLE
Building conda environment that includes Pyleoclim

### ISSUE THREAD

**Issue by danielbabin** [LinkedEarth/Pyleoclim_util#264]
Hello everyone,

I've got a pretty sophisticated environment that I would like to add Pyleoclim on top of. Because Pyleo is not available through condo, I need to do a pip install at the end. I've attached my environment file. 
[environment.txt](https://github.com/LinkedEarth/Pyleoclim_util/files/9639401/environment.txt)

Because of the number of packages involved in the environment, I've found it's better to use [Mamba](https://mamba.readthedocs.io/en/latest/) instead of Conda. I've waited 10 hours or so for conda to solve. Mamba can do it in just a few minutes.

The environment solves quickly, but the pip installation of Pyleo fails. I've attached the readout.
[terminal readout failed pip Pyleo.txt](https://github.com/LinkedEarth/Pyleoclim_util/files/9639408/terminal.readout.failed.pip.Pyleo.txt)

I'd like to get this worked out. Up until now I've been switching environments to use Pyleo, but I'd really prefer not to. And others shouldn't have to switch environments to use different parts of my code. 

Thanks! Let me know if you need anything else. I might have missed something because I've somehow made it this far without ever posting to ask for help. 

Cheers
Daniel

**Comment by CommonClimate** [comment]
Hi @danielbabin , thanks for looking into this. The issues is called by llvmlite, which appears to be used by numba. @fzhu2e is the most knowledgeable about this but he is very busy at the moment, so I am not sure when we might be able to fix this for you. Stay tuned.

**Comment by khider** [comment]
Conda may have issues because it's trying to resolve the best possible outcome for the various packages. If you have this particular environment on your computer, it might be useful to fix the versions for the packages. Another fix would be to only mention the packages that are being installed for the work rather than their dependencies + packages. 

The last fix I could think of is to install numba via conda before the pip to Pyleoclim.
