### ISSUE TITLE
Anti-aliasing feature for all spectral analysis methods

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#277]
Currently, the anti-aliasing feature is coded inside the WWZ method.
I'm planning to create a method for the PSD class so that anti-aliasing can be applied to all other spectral methods.
The original structure of the WWZ method will not be touched, and only a new method is available for PSD objects, so no conflict is expected.

**Comment by fzhu2e** [comment]
Implemented in commit d1c6bcc

**Comment by CommonClimate** [comment]
Nice work @fzhu2e ! Two small things that should be easy to take care of:

- applying the filter is a little slow for 2000 PSDs (O(1min)) so we should incorporate a progress bar for MultiplePSD objects of a certain size (say, over 20 series?). Or have it by default in all cases unless `pbar = False`, perhaps. 
- I wonder if the application of the filter should be recorded somewhere. `Series` objects (and children) now have a `log` property that keeps track of the various transformations applied to the data. I wonder if we should generalize this concept to other objects. At the very least, this should update some PSD labels upon plotting so users know (and remember to tell their readers) that they applied this filter...

**Comment by fzhu2e** [comment]
Progress bar implemented in commit b19eae6. The argument is named `mute_pbar` following the convention in the `MultipleSeries` class.

Yes, I think the `log` system will make the debugging process of data analysis much easier. I have suggestions for the design:
- `keep_log` always set to `True`, i.e., we don't need this extra argument in the arg list, as it won't add much burden to the processing anyway.
- I see the current design is a tuple of dictionary, with the method name and the args for the method noted in the dictionary in a same level. Below is another similar design but with a nested dictionary structure that could be more useful for reuse of the arguments for future steps.
```
(  # tuple to note the processing steps; it is un-mutable and ordered, so there's no need to specify the number of the step,
  # each dictionary notes the method name and its arguments
  {method: name_str_1, args: args_dict_1},
  {method: name_str_2, args: args_dict2},
)
```
With this structure, we may access the method name of the 1st step like:  `Series.log[0]['method']` and its args like `Series.log[0]['args']` and they can be reused later.

**Comment by CommonClimate** [comment]
Hi @fzhu2e ,
thanks for implementing the progress bar for MultiplePSDs.  Re: log, the design you propose should be discussed in the original log thread for ease of reference. I will let @khider weigh in on it before we make a decision. 

Re: "We could create a utility function to create a log for the current method, so every time we can just call this function if we think it's worth logging, instead of typing a line of similar code that's different in detail."  I am not sure what you mean. If you look at the various methods (e.g. `Series.standardize()`), they add the log internally because the details vary from method to method. In practice it's only 1-2 lines of code, so there is no need for a dedicated method. Or I am missing your point?

Re: "The log should be inherited so that we know the history/source of the current object": yes, but instead of users having to type `psd.log = ts.log`, I was thinking that this would be done internally (here, within `.spectral()`), adding to the existing log (possibly empty). That would be one way to track e.g. whether standardization has been applied, as spectral() does that by default, and users don't always know.

**Comment by fzhu2e** [comment]
Re: The utility function. It notes down the name of the current method along with the arguments being set, and it should be called in the end of each fundamental method that worth logging. Say a higher-level method A calls some lower-level methods B, C, D. Each of them (A, B, C, D) calls the utility function once, and we don't have to write different lines for them, but all details can be noted down. It's a bottom-up design. 

Re: `psd.log = ts.log`. Yes, it's called internally; not done by the users. My pseudocode is trying to say that we replace the original call with that call + an extra step.

**Comment by CommonClimate** [comment]
Thanks for the clarifications Feng. I support these changes but it might be worth opening a different issue so we can better track it, and implement the utility function for other logging calls. Perhaps you can write that function and show us an example of how it works, and we can see how it would fit in our December hackathon? Or later, because this is not very high on the priority list right now.

**Comment by khider** [comment]
Not sure log is necessary for PSD/Scalogram since we don't do much with them. However wave_args should probably contain that parameter values used to obtain the PSD/Scalogram

**Comment by fzhu2e** [comment]
The log system? Perhaps delegate to the team, as I need to work on the cfr paper and other CESM tasks.

**Comment by CommonClimate** [comment]
Deborah made a good case that this is not useful for the log system, so we'll look into a way to adding this to `wave_args`. I'll close this now - good work!
