### ISSUE TITLE
plot_trace legend now shows the same name for all traces instead of just doing one

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#602]
Before we would only do one legend entry for the first trace. now showing all.

**Comment by CommonClimate** [comment]
That was done to save space, otherwise the legends are entirely unmanageable for multi panel plots with more than ~5 traces. Can this be a switch, at least?


Julien Emile-Geay,  professor
University of Southern California


On Jul 17, 2024, at 14:37, Deborah Khider ***@***.***> wrote:

﻿

Before we would only do one legend entry for the first trace. now showing all.

**Comment by khider** [comment]
Well, that's the problem. Instead of showing the space saver, it was showing everything. So I went back to only showing one.

**Comment by khider** [comment]
Addressed by https://github.com/LinkedEarth/Pyleoclim_util/commit/5ad1375e7eec7957708f69c755eedf397416add8
