### ISSUE TITLE
Make Pyleoclim resistant to invalid LiPD files

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#98]
**Is your feature request related to a problem? Please describe.**
Had issues utilizing the mapAllArchive function on a Lipd object (a collection of lipd files) due to one file missing the archiveType key.

**Describe the solution you'd like**
We should consider making pyleoclim lipd utilities resistant to the occasional errant Lipd file.

**Comment by khider** [comment]
Another option is to validate a LiPD file upon loading and remove offending files from the dictionary. It might become very cumbersome to work around all the invalid files since we have to make assumption.

In this particular instance, the archiveType is missing so we would have to either guess one or default to 'other', which is how bad values (i.e. not in ontology) are handled for now.

**Comment by CommonClimate** [comment]
Agreed. We can't make pyleoclim resistant to all data issues, and arguably we wouldn't want to: if some key information is missing, there is nothing to do except notify the the folks who generated the LiPD file/compilation. If you brush too many issues under the rug, they always come back to bite you.

**Comment by khider** [comment]
Requires a change in the LiPD utils package to parse API response to the validator.

**Comment by khider** [comment]
There is a discrepancy between the Python validator and the one on lipd.net. Should decide how to handle ensembles (number of columns discrepancy)

**Comment by khider** [comment]
Updates to Lipd loaded and mapAllArchive() to handle invalid and semi-valid lipd files in commit [37f075b](https://github.com/LinkedEarth/Pyleoclim_util/commit/37f075b27aeed73988bcb889b6d784bc75114ea5).

_Update to loader:_
Two arguments were added:
- validate: which triggers the validator from the lipd utilities
- remove: remove unvalidated files. Note that an exception is made for the error due to ensemble representation.

By default, both are set to false since validation can take a fair amount of time. We recommend using the online validator before using new files. For compilations, curation process and publication should remove any validation problems.  if remove is set to true, the dataset will be ignored. This is not always a wanted behavior since most functions will work with a small amount of missing metadata. 

_Update to matAllArchive:_
Although a valid LiPD file should have an archiveType, bypasses the lack of value and set it to 'other' for mapping.
